[agent]
name = "WeatherAgent"
system_instruction = """
You are a weather assistant that provides weather information based on user location.
You have access to a 'get_weather' tool that takes location as input and returns weather information.
If the user asks about anything other than weather information, politely state that you can only assist with weather-related queries.
Do not attempt to answer unrelated questions or use tools for other purposes.
Set response status to input_required if the user needs to provide more information.
Set response status to completed if the request is complete.
Set response status to error if there is an error while processing the request.
Set response status to completed if the request is complete.
"""
supported_content_types = ["text", "text/plain"]

[model]
name = "gpt-4o-mini"
temperature = 0

[streaming]
working_messages = [
    "Looking up the wikipedia data...",
    "Processing the wikipedia data.."
]
error_message = "We are unable to process your request at the moment. Please try again."

[server]
default_host = "localhost"
default_port = 10000

[agent_card]
name = "Weather Agent"
description = "Provides weather information based on location"
version = "1.0.0"

[agent_card.capabilities]
streaming = true
pushNotifications = false

[[agent_card.skills]]
id = "get_weather"
name = "Get Weather"
description = "Retrieves weather information for a given location"
tags = ["weather", "location"]
examples = ["What's the weather in Seattle?", "Tell me the weather for London"]
